import {
  collection,
  doc,
  addDoc,
  deleteDoc,
  updateDoc,
} from "firebase/firestore";
import { db } from "./config";

/**
 * Saves data from the recipe collection
 * @param {*} data data to be saved
 * @returns firebase autogenerated id or null
 */
export async function save(data) {
  try {
    const docRef = await addDoc(collection(db, "recipes"), data);
    return docRef.id;
  } catch {
    return null;
  }
}

/**
 * Removes a certain document from recipe collection
 * @param {*} id task id
 * @returns (boolean) if successful
 */
export async function remove(id) {
  try {
    await deleteDoc(doc(db, "recipes", id));
    return true;
  } catch {
    return false;
  }
}

/**
 * Updates data from the users collection
 * @param {*} data data to be saved
 * @returns (boolean) if successful
 */
export async function updateUserProfile(data) {
  try {
    await updateDoc(doc(db, "users", data.uid), {
      displayName: data.displayName,
    });
    return true;
  } catch (error) {
    console.log("Failedddd", error);
    return false;
  }
}
