import { collection, doc, addDoc, deleteDoc } from "firebase/firestore";
import { db } from "./config";

/**
 * Saves data from the recipe collection
 * @param {*} data data to be saved
 * @returns firebase autogenerated id or null
 */
export async function save(data) {
  try {
    const docRef = await addDoc(collection(db, "recipes"), data);
    return docRef.id;
  } catch {
    return null;
  }
}

/**
 * Removes a certain document from recipe collection
 * @param {*} id task id
 * @returns (boolean) if successful
 */
export async function remove(id) {
  try {
    await deleteDoc(doc(db, "recipes", id));
    return true;
  } catch {
    return false;
  }
}
